### ISSUE TITLE
Not able install using pod - Seems to be private repository

### ISSUE THREAD

**Issue by HimanshuChowdharyIndia** [Skydio/skydio-specs-ios#1]
Hi skydio,

I was trying to install skydio-sdk-ios in my application but did not able to do due to access issue.

I did not see any notes. I tried using below mentioned pod :

pod 'skydio-specs-ios', :git => 'git@github.com:Skydio/skydio-sdk-ios.git', :tag => "15.9.0"

Please correct if I am wrong, if not please let me know whether it is private or public sdk / repository.

Please find below image showing error I am facing

![skydio](https://user-images.githubusercontent.com/40492883/149538024-a49a8e82-28c7-4a3e-b85b-3378b5ac19f9.png)

Best Regards,
Himanshu

**Comment by matt-donahoe-skydio** [comment]
It's was a private repo, sorry.
